version: '3'
services:
  web:
    container_name: docker-db-connection-handle
    restart: always
    build: .
    ports:
      - '81:3000'
    links:
      - db
  db:
    container_name: mongodb
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - shared_database:/data/db
volumes:
  shared_database: